package protocol.command;

/**
 * @author jmx
 * @date 2020/3/10 8:45 AM
 */
public interface Command {

    Byte LOGIN_REQUEST = 1;

    Byte LOGIN_RESPONSE = 2;

    Byte MESSAGE_REQUEST = 3;

    Byte MESSAGE_RESPONSE = 4;

    Byte LOGOUT_REQUEST = 5;

    Byte LOGOUT_RESPONSE = 6;

    Byte CREATE_GROUP_REQUEST = 7;

    Byte CREATE_GROUP_RESPONSE = 8;

    Byte LIST_GROUP_MEMBERS_REQUEST = 9;

    Byte LIST_GROUP_MEMBERS_RESPONSE = 10;

    Byte JOIN_GROUP_REQUEST = 11;

    Byte JOIN_GROUP_RESPONSE = 12;

    Byte QUIT_GROUP_REQUEST = 13;

    Byte QUIT_GROUP_RESPONSE = 14;

    Byte GROUP_MESSAGE_REQUEST = 15;

    Byte GROUP_MESSAGE_RESPONSE = 16;

    Byte HEARTBEAT_REQUEST = 17;

    Byte HEARTBEAT_RESPONSE = 18;

    Byte REGISTER_REQUEST = 19;

    Byte REGISTER_RESPONSE = 20;

    Byte CONTACT_ASK_REQUEST = 21;

    Byte CONTACT_ASK_RESPONSE = 22;

    Byte CONTACT_CONFIRM_REQUEST = 23;

    Byte CONTACT_CONFIRM_RESPONSE = 24;

    Byte LIST_CONTACTS_REQUEST = 25;

    Byte LIST_CONTACTS_RESPONSE = 26;
}
